name: First Workflow

on:
  push:
     branch: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Primer-Trabajo:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup JDK 17
      uses: actions@setup-java@v1
      with:
         java-version: '17'
         distribution: 'adopt'
         cache: maven
         
    - name: Build with Maven
      run: |
         #cd src/test/java/mainScripts/
         mvn -B package --file pom.xml
         
    - name: Run java class
      run: |
         javac Tests.java
         
         
      
          
