name: First Workflow

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Primer-Trabajo:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup JDK 17.0.3
      uses: actions@setup-java@v1
      with:
         java-version: 17.0.3
         
    - name: Build with Maven
      run: |
         mvn -B package --file pom.xml
         cd src/
         cd main/
         cd java/
         
      
          
