name: First Workflow

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Primer-Trabajo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Prueba
        run: mvn clean test

      - name: Run a multi-line script
        run: |
          cd src/main/java/mainScripts/
          exec Main
          javac Main
          java Main
